.TH MICTOOL 1
.SH NAME
mictool \- formatiert MPR-Dateien aus JMic als HTML oder LaTeX.
.SH SYNTAX
.B mictool
[\fB\-\-help\fR]
[\fB\-\-version\fR]
.IR MPRDATEI
[\fB\-\-debug\fR]
[\fB\-\-html\fR]
[\fB\-\-latex\fR]
[\FB\-\-title \fITITEL\fR]
[\fB\-o \fIAUSGABEDATEI\fR]
.SH BESCHREIBUNG
.B mictool
liest eine MPR-Datei in Version 4 (kompatibel zu JMic 1.4) ein und formatiert diese als HTML zum besseren Lesen.
(Beachte: MPR-Dateien sind text-basiert, aber die wichtigen Daten sind binär-kodiert.)
.SH OPTIONEN
.TP
.BR \-o ", " \-\-output " " \fIAUSGABEDATEI\fR
Formatiert die \fIMPRDATEI\fR als HTML oder LaTeX abhängig von der Datei-Endung und gibt sie in der angegebenen Datei aus.
.TP
.BR \-\-html
Stellt die Ausgabe auf HTML.
.TP
.BR \-\-latex
Stellt die Ausgabe auf LaTeX.
.TP
.BR \-\-debug
Stellt die Ausgabe auf Debug.
.TP
.BR \-\-title " " \fITITEL\fR
Setzt explizit den Titel für HTML- oder LaTeX-Dokumente.
.TP
.BR \-h ", " \-\-help
Zeigt die Hilfe.
.TP
.BR \-v ", " \-\-version
Zeigt Versionsinformationen.
.SH AUTOR
Geschrieben von Hans Kirchner, 2014.
