.TH MICTOOL 1
.SH NAME
mictool \- formatiert MPR-Dateien aus JMic als HTML
.SH SYNTAX
.B mictool
[\fB\-\-help\fR]
[\fB\-\-version\fR]
.IR eingabedatei
[\fB\-\-debug\fR]
[\fB\-\-output\-html\fR \fIAUSGABEDATEI\fR]
.SH BESCHREIBUNG
.B mictool
liest eine MPR-Datei in Version 4 (kompatibel zu JMic 1.4) ein und formatiert diese als HTML zum besseren Lesen.
(Beachte: MPR-Dateien sind text-basiert, aber die wichtigen Daten sind binär-kodiert.)
.SH OPTIONEN
.TP
.BR \-o ", " \-\-output\-html " " \fIAUSGABEDATEI\fR
Formatiert die \fIEingabedatei\fR als HTML.
.TP
.BR \-d ", " \-\-debug
Schreibt den Inhalt von \fIEingabedatei\fR nach stdout (Standard-Ausgabe).
.TP
.BR \-h ", " \-\-help
Zeigt die Hilfe.
.TP
.BR \-v ", " \-\-version
Zeigt Versionsinformationen.
.SH AUTOR
Geschrieben von Hans Kirchner, 2014.
